language: ruby
rvm:
- 2.1
python:
- 3.4
sudo: required
branches:
  only:
  - sources
install:
- bundle install
- sudo pip install ads
before_script:
- git config user.email "Travis CI"
- git config user.name "Travis CI"
- git checkout -b master
- python scripts/fetch_pubs.py -k ${ADS_KEY} -d _data/publications.yml
script:
- bundle exec jekyll build
after_script:
- git add -f _data/publications.yml
- git commit -m "updating publication list"
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
env:
  global:
  - secure: GpbhtvqtWn4KC0lkfJpjiRX3I1Kv+aKvw0xO5dEE9uCBndc7RgCSDf529lFrcxOzDLYOcse76nOkz7hzY0zRhvib3sVWfNmivJNHnPFa9v2FkHhBEsynMXX8m1OcA1u4efLgkZDqZp3GTsd9ZZ8cBA4NFoiheqaM3Lt46DVFSYRW5kviZWJdS3SoyNz8RK8NR03Q7oZvHbVx6tpPJnfJaB1+/xe8aJWBKOkKMjP2OYD4pdNv1n76kRLAe9NWRWYJIdpHuSpeHSt42QlgoEtMbCKLjUdJANLkumjPR5P9zzeILPkHJaztqngk0bw17eDExFqB4DqqhgJgWhjPnXYBWyb2OQY0RgPugkws7R87mtrh5XUZMlCkJRAdH4oXygqAM1R3lNqu/d5Acqzwj7BSBq+bu7uZAPe0IgvMaB5b+r+44G0Hj6rqegU0igPpLtYr2/wbCnC/cJUqRtZcWFxEM+rkJuP5zrIPfguSZjG3F+xiMTuy3nCtxU3K3rnoIici5rNUYWAqsXT4XW7fWfSb5VoL1OPnsfIQn8D5pMKn/1LeFFljWAaylTNRQ2BEBRFzqPwlT8qjUbYp6kxygnalnhffEYBXs77bw/3liBxFilXrHV9ZCFWcddnvjOgetiXyV/9X6fJ7F7WU16fC5SnT6x28tH90WAlG12OMpWSyKG0=
  - secure: BPgUXN+d75mpo1y/TCawRqC8JR3k/rbqRD8nGERte0aP+83dJT2VI7BCNn3S+a7QtQHvX6yZvj9WN757DU6ehyT07iq5/KBfrr/b5YAUriokDVC/XlNHF7MHcg7179ZeA+O/m4gpmH8Pj3wPPJXfCCAMd1xXoh4F+j19X9Ec8Vge/5TLJ8St5TBobWP97x4AqePbVOfOwx94vKWVncR7T08oA2qm+VfVgjTYN2Qy8jS13IXWcvimTg3cqzAD2lzZZbgnqM+rztrFVJ0HL0AdhwPMRpbJYe2uE0vWq9lDtXkFkc+WoV7qGfiNFQGQArTXRsEZT91Cgtw4Yuk0WGcNOzyws5u2UiqDvAm1b9U5Zo9vmiG3BmrWiw3VJ48j7/EHjOPMIc6FTSBABb3f4uud8MH6ToBhyzX3gq+UCwAB0ZYeUIBE/wVNEhLnaYLIMOC9Uqq5161ixcC3TPUPbvq59QaYfp1ZB4nYdamsPpv/4IWOTsOGQZm4Lx3TJLVKRSH+xyHggWnOO6O5vcEEL9x1wTXTtyyG3nozdRSzp178bknsz6429UTrOK04vy6XjTHAbQnrF5ujEreFlCus01arafiC8AKiE3ltbv2V72Eca0TBfLKu2yTv5GDClvWCJyI9zC8+CteYpcV8Ob/TBdoC5KL42IQRxj7TcZzmAXHvWSU=
