language: ruby
rvm:
- 2.3
python:
- 3.5
sudo: required
branches:
  only:
  - master
addons:
  ssh_known_hosts: wtb2.rice.edu
install:
- sudo apt-get install sshpass
- gem install bundler
- bundle install
- sudo pip install ads
before_script:
- python scripts/fetch_pubs.py -k ${ADS_KEY} -d _data/publications.yml
script:
- bundle exec jekyll build
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; sshpass -p ${RU_PASS} rsync -a --delete _site/ ${RU_USER}@wtb2.rice.edu:${MOUNT_DIR}; fi'
env:
  global:
  - MOUNT_DIR="/mnt/web/solar_dot_rice_dot_edu"
  - secure: ZNLSXzkZbuzgkSjtJtAS046Jt2tK0ZpSf027PWKzBNK2L1NQVj7bW2XuLGyJ1bLmIbnCAfIq8iVobmK8tq/tSYeRCro2HNZxB7S3Y/GHlUGPHcDG8sWdebQ7o6L9Z89DuUJtuE2UPdvcOzwuIH2Rw+gtwBk+Dx6TyWOsewBPBM9WkIZDCd/GvoseK6jzDlkP1fVchH24FlZ04F0bkGS3af0YxVM7lDOpdR5ITuH7efwEhUivX1d6rtX0eWY+XT56mEIhZCtcy6MzwgdtY2AvYik5w8EykQChqEWSDyrH96dom/bvKy90QUazrxzpscYsa50FIzNKgmzFy8RoEdF45aJsoeITiXXr7CGsrOnYiaEIj8LQA+QOK/z0Uq3UmrCampluG8r00EPcjgh4P1fIZL5UoXvb46uSaSwjeRGQdjwgDX+xLa/cp5S96k0uU9zOlyctcMc9Xt3o94AAJ5JqXcZrTa2ccQWp6Zw2//HaP2jCH7LdkK5Zpb3rFdGLXwfb0tuyZfyj+exyMBFzKUtFVYP4R094jVGl+oTDH4YDahIU+KOm03tgSzRlsYZuyqEK70JO97dZPnhlF00ZlqGBBF8cXK73SAoLJ2sJYVWpM/V1BgliubtmNwsYdsDOEWt3xwBOENV9Fr6hIyLEIt6A8SK14DZ2NNUDlRoj1SrVYbQ=
  - secure: dgnyFzXAEXsyotL4Qr7rQdgvydRfboEzvQeRyxmyRbatquvlfAv4Aywgzg0lJBp8w7f6zCgmJA/Oj34CfcnGDmwZz2MHfxA9nmrMr/75g0SjpHH7vGPWITtRV/T+3BVoprn6tR595RQWguJhF9l9w/D8a1M6l9QdwJ5xsbNcEDQESwdUfDurYu0TxUhhKRV8EAjxOiT5DprKsSdinaAk8+tOg9ScA9Clh0jo+Co4c7eJyldMZQ8iRiOCX11cWpTfH+GnRiZibL0cB+/3WVxEmYZyiCcjQXSdEjYyDiFGjTpGxErILaFBzI0exlRpgSHn/ad6C8X7FA598H+e6dywnvV2XByQ688DBkLIouuS9TUz1CLwhKgCXyvAjD0VpeRjOzpA1R6HgpcqZvCMCfSFXp8RtQ7ct+l0ZyGdIJ9Gok2e2gPsfPX8yvoAER3/n1ugb+8/G8NsyoQaE9FE1+GPXERaoyIlV53dlojS39iJWWNRDEYFAQ/arbl+yniGINEOxZHUtw1vODfXO4eKOzL/M8VGnZx4ed5yc9kVk6GS49UUekQL1bX0lvwjJMBxnOccqx5TUvZ/xNvJo5CMLQoma0Ih0knMuz5H/XA9lfXAOHMFPYe07IUae0oygX5QN+9ugFrK4UBIRRIdHUYLxJGU1ATrUCLs3MsgB/QTXAQ6n3c=
  - secure: YBo00+UotjsBUm40nPG5HtuyvaCf1Y8+17UbrvUepCI2aXBEW6uNqFxgVvdyu1vvfrpTcyafGr7hKeJSapDQiqRdfHKyHc7M4f/351Hy9UobB8UJx9g8Lypv2AgTUAoRnIEZjw1IIQC7aTfRI7vz8zctoQuFwOF0VsCwjy/U54UD5YziSOtmJkq3QO1F0wti651Ik1htAsA2MS2Si2exkIs3qFNBSH0xyKNRQ2Hl57SS86pMpUjK6OjzTI60gEwNVbaQpsqW5mNCzA3O9cVidEmGbNMu2IroEhDyvKBhpOiHwr3fj+/wvpkpNB7SqzkAZFmhmSI+aP1e0WKAsSGBFbUFRRyZIRmd5QIJ131Cnk5MGbKCWaIJfV3KnM/cyryhlfhYkdv7L+czCxvaRuFnqjW+38Kit998v4C2E0n2MoTFDwZkd2bIMHaoaC3n5aG/s8cDs1e6A9dFWtUW5OWzuiIoVx3BVcGkBHBQUScQPJvUBz7zFkYZ2iMOTT2gvJ7K6jA+OQQY24dEAgPTu1+x8nL80xgTzMModLwmCKJOGkh0r4vNm1JonUf2nWYbV7SG9gwC8E58RaquMTr4UldPBD+EJx20s6+6c54EAD+l/Ur1dmeP5KNV6sG69zqy/4Q4CFdLYQqRpGs4Wq6RB64TjuHl+CsAuWQK90BD3CzvHOQ=
