language: ruby
rvm:
- 2.1
python:
- 3.4
sudo: required
branches:
  only:
  - master
install:
- sudo apt-get install smbfs
- bundle install
- sudo pip install ads
before_script:
- python scripts/fetch_pubs.py -k ${ADS_KEY} -d _data/publications.yml
script:
- bundle exec jekyll build
after_script:
- mkdir -p ${MOUNT_DIR}
- sudo mount -t cifs -o username=${RU_USER},password=${RU_PASS},dom=ADRICE //storage.rice.edu/PhysAstro/Public/www/solar.rice.edu ${MOUNT_DIR}
- sudo cp -r _site/ ${MOUNT_DIR}
- sudo umount ${MOUNT_DIR}
env:
  global:
  - MOUNT_DIR="${HOME}/solar_dot_rice_dot_edu"
  - secure: "ZNLSXzkZbuzgkSjtJtAS046Jt2tK0ZpSf027PWKzBNK2L1NQVj7bW2XuLGyJ1bLmIbnCAfIq8iVobmK8tq/tSYeRCro2HNZxB7S3Y/GHlUGPHcDG8sWdebQ7o6L9Z89DuUJtuE2UPdvcOzwuIH2Rw+gtwBk+Dx6TyWOsewBPBM9WkIZDCd/GvoseK6jzDlkP1fVchH24FlZ04F0bkGS3af0YxVM7lDOpdR5ITuH7efwEhUivX1d6rtX0eWY+XT56mEIhZCtcy6MzwgdtY2AvYik5w8EykQChqEWSDyrH96dom/bvKy90QUazrxzpscYsa50FIzNKgmzFy8RoEdF45aJsoeITiXXr7CGsrOnYiaEIj8LQA+QOK/z0Uq3UmrCampluG8r00EPcjgh4P1fIZL5UoXvb46uSaSwjeRGQdjwgDX+xLa/cp5S96k0uU9zOlyctcMc9Xt3o94AAJ5JqXcZrTa2ccQWp6Zw2//HaP2jCH7LdkK5Zpb3rFdGLXwfb0tuyZfyj+exyMBFzKUtFVYP4R094jVGl+oTDH4YDahIU+KOm03tgSzRlsYZuyqEK70JO97dZPnhlF00ZlqGBBF8cXK73SAoLJ2sJYVWpM/V1BgliubtmNwsYdsDOEWt3xwBOENV9Fr6hIyLEIt6A8SK14DZ2NNUDlRoj1SrVYbQ="
  - secure: "hti+96EQjXnRWHLRpVTB971uxcWV5b6CqZKpKa/TdiL3Q2we2O7fqo72CtnJEO4IEuwJ0194au0H440qOjxys2JvqX/dugg9KqaJsZdDT9JQOSUayac0IrBS5D4lla7RQzoC2o3oZlcW8Ewyim/NSXv7DvjKXELX8MGJX557eE6T1n9io2SaFfQKgLzgzgCVCvyS3SEaZ7p6be/H4n8gOBrHBu9TWP8hF8x0wXjF9ICW0MpRkhUwBlGTy7G6k67MZkeKNu2Ezr8OI4ii3gUr21u/sBelhRC+kcDiJ4GmwkKTWgmGpu2AX4RV28KbkMC4eWTxWqc4tjZtwrOo8K6LIyb/Ws8FB82BlgAeCTy0ykzkSWPNrCC0cVFPKEZjHMw6Q4zVJVfUqxqOGNleRtGeoDL77jjnhFxmnu141Gk7zGN/Ak7TCMWsF0cR88UwgBRLmUoVorFmwky9Fj48+71piJu5CG4x78Qc/N1yZSN9jy/chUw6HhIwmyGZAlnl0eSlqoA0BqLoA3F9aIalZQW9KZUfQsdHNirbO1H/EXB6FFbkQn8/yVTJFKYuTUD4s1Dk/oD1QzHeOMv19uU1CKUC6FocrygE1w7n2mIGOJ36iEUQUaVWABgL6lGwgZwF3HvhvYxYd1RMESg09a+fNT17CT9XbkPftRtzm8ep/jlirmk="
  - secure: "R19zKls414J2NQ8rcvad9rbCWUbhICE5zMkVUqu1VKofV9eGWR87w/CEcSRG7u/gex2iXRBlaTVKZJfRUE9WEbFn3oJsqIyJANinW20E0zDNpnRFyoAHRHUkOtY8dHP/23m1UZnXKv9rHZmdEpQtvqKp+99LU+Jr4Rkth3h40JnXLxxgz3CGkiSwd1lzs0/mO+2rE2yDQHrONKH1dThH+4mKDbrYy3B8yG2X313CWu7KzkkSmLz3YsFyLQ8aSEQgubMzptwarUFOKfyYfIWazfOysJGbxkiwR7Q7N3nozAzAF/V9GilISHC42GX4o+cRsppk6df14bAq7IvNBKn4T3ZogHsUngUP5LmTQEhrmqUq9uS5qfSUXKouagBzOFGuHU8VXQ91xD7y2VSsjkQrKss4x8FZJ77ZSvScoSUbE/4RjmHEy8SQ9jRp5SE75VNtbP5zJ7QUFy0xmCGs9mAtPAjZRl0zhBkjWFkhmH97oJWWLbP03vMagkxfraz5fPtvcyQAaVKp6R8xHQH9ukdlDenMjLD7u4bl8ZRWy7CGMQvEZB3+qTI+pmq65z9SU6Zw5K9TS+0fNX7XJQwwxowEZrDsMF/bcWAGJDVB0ycImbkhk0NhSdp3OznvFUkdQAUd8MZz9IIOS+SaIbJXlsuZkT4BUz0QaR2NyUiXSOIGt/8="
