language: ruby
rvm:
- 2.3
sudo: required
dist: trusty
branches:
  only:
  - master
addons:
  ssh_known_hosts: wtb2.rice.edu
install:
- sudo apt-get install sshpass -y
- gem install bundler
- bundle install
- sudo pip install ads
- sudo pip install PyYaml
script:
- 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; make build_pr; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; make deploy; fi'
env:
  global:
  - MOUNT_DIR="/mnt/web/solar_dot_rice_dot_edu"
  - secure: Xst8R6fPquX2z3IPvwIlHPg6H+5Bu6g+xrN0VpEVxj2uWJ6EUXnjsJaX+fQf7rjUvF9NvzJQlfDgbBOP5q+DlX6SoDv+fsx5orGLg+/46pVmsmFhjfRwTGHH1j58ubafAq5CUYDGzTafANaj2GY9uH/c194PAZiHYyEvn6HKnpZYu/+Cr7nee/e2+ma8knK2gwKMpfDjoIvGisLJUa6I7XiC0rYocZZc7F2diZ1G5JGtZDTvVUQUmHOd6vMWpvMlVqMqKKFFGY5OAcpStHbBRxI9aw4ULTOZ5VNeCJEOEz3R/FnckrcfUKSnX3Frx45PcRm+NfCjhUiRKAAfZfNoLB67zGv6mUoil1tHvv94jQyp+Jzi9cslhHfCPjNUEnu9oGX9y9g5NXXDaYRR8sU/+hGpZj41rXg2jvR9lxFoQ1M6s8Zu/eyfOQ+cwPyIy1Zqy81BBHd4ypqxrxxt0EqsOnZ/8E7rzH3vDVVV8gAXpACsHnwFozir9hxyEfUjYzdP/gWiPs706lTsrMg3Bc/ZKh06gPCYCbtIPBHX11kU7CqHXBM7EqZsXOn6k7uXI0xdbQ+ru9GNeC5AJ2JZLPAIOi57Ro7CGTa6F41Q/QNdu0gOWMF7hFbSSk9ION/9dbJRXPqUpM70TkC0eGoKBiNFmkG9wIo5QTczprxMxwsggPo=
  - secure: dgnyFzXAEXsyotL4Qr7rQdgvydRfboEzvQeRyxmyRbatquvlfAv4Aywgzg0lJBp8w7f6zCgmJA/Oj34CfcnGDmwZz2MHfxA9nmrMr/75g0SjpHH7vGPWITtRV/T+3BVoprn6tR595RQWguJhF9l9w/D8a1M6l9QdwJ5xsbNcEDQESwdUfDurYu0TxUhhKRV8EAjxOiT5DprKsSdinaAk8+tOg9ScA9Clh0jo+Co4c7eJyldMZQ8iRiOCX11cWpTfH+GnRiZibL0cB+/3WVxEmYZyiCcjQXSdEjYyDiFGjTpGxErILaFBzI0exlRpgSHn/ad6C8X7FA598H+e6dywnvV2XByQ688DBkLIouuS9TUz1CLwhKgCXyvAjD0VpeRjOzpA1R6HgpcqZvCMCfSFXp8RtQ7ct+l0ZyGdIJ9Gok2e2gPsfPX8yvoAER3/n1ugb+8/G8NsyoQaE9FE1+GPXERaoyIlV53dlojS39iJWWNRDEYFAQ/arbl+yniGINEOxZHUtw1vODfXO4eKOzL/M8VGnZx4ed5yc9kVk6GS49UUekQL1bX0lvwjJMBxnOccqx5TUvZ/xNvJo5CMLQoma0Ih0knMuz5H/XA9lfXAOHMFPYe07IUae0oygX5QN+9ugFrK4UBIRRIdHUYLxJGU1ATrUCLs3MsgB/QTXAQ6n3c=
  - secure: YBo00+UotjsBUm40nPG5HtuyvaCf1Y8+17UbrvUepCI2aXBEW6uNqFxgVvdyu1vvfrpTcyafGr7hKeJSapDQiqRdfHKyHc7M4f/351Hy9UobB8UJx9g8Lypv2AgTUAoRnIEZjw1IIQC7aTfRI7vz8zctoQuFwOF0VsCwjy/U54UD5YziSOtmJkq3QO1F0wti651Ik1htAsA2MS2Si2exkIs3qFNBSH0xyKNRQ2Hl57SS86pMpUjK6OjzTI60gEwNVbaQpsqW5mNCzA3O9cVidEmGbNMu2IroEhDyvKBhpOiHwr3fj+/wvpkpNB7SqzkAZFmhmSI+aP1e0WKAsSGBFbUFRRyZIRmd5QIJ131Cnk5MGbKCWaIJfV3KnM/cyryhlfhYkdv7L+czCxvaRuFnqjW+38Kit998v4C2E0n2MoTFDwZkd2bIMHaoaC3n5aG/s8cDs1e6A9dFWtUW5OWzuiIoVx3BVcGkBHBQUScQPJvUBz7zFkYZ2iMOTT2gvJ7K6jA+OQQY24dEAgPTu1+x8nL80xgTzMModLwmCKJOGkh0r4vNm1JonUf2nWYbV7SG9gwC8E58RaquMTr4UldPBD+EJx20s6+6c54EAD+l/Ur1dmeP5KNV6sG69zqy/4Q4CFdLYQqRpGs4Wq6RB64TjuHl+CsAuWQK90BD3CzvHOQ=
