# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [smart,tables]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Solar @Rice
name:             Solar@Rice
tagline:          'Rice Solar Physics Research Group webpage'
description:      'Solar Physics Research Group at Rice University'
baseurl:          /
url:              http://solar.rice.edu

author:
  name:           'Will Barnes'
  email:          'will.t.barnes@rice.edu'

include: ['_pages']

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb

paginate:         5
paginate_path: "page:num"

# Collections
#collections:
#  research:
#    output: true
#    permalink: /research/:path/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rice-solar-physics/group_webpage

#stuff from sampa research group template
# Sections on the "people" page.
roles:
  - {key: faculty, name: Faculty}
  - {key: ressci, name: Research Scientists}
  - {key: grad, name: Graduate Students}
  - {key: ugrad, name: Undergraduate Students}
  - {key: alum, name: Alumni}

front_page_news: 8

navigation:
    - title: Home
      link: /
    - title: People
      link: /People.html
    - title: Research
      link: /Research.html
    - title: Publications
      link: /Publications.html
    - title: Software
      link: /Software.html
    - title: Resources
      link: /Resources.html
