# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [smart,tables]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Solar@Rice
name:             Solar@Rice
description:      'The <b>Solar Physics Research Group</b> at <b>Rice University</b> uses computational modeling and observational tools to explore a variety of topics in solar and space plasma physics. Our current <a href="{{ site.base}}/Research.html">research projects</a> range from forward modeling of nanoflare-heated solar active regions to magnetic interactions between stars and planets. We are housed within the Department of Physics and Astronomy and located primarily in <a href="http://www.rice.edu/maps/Rice-University-Color-Campus-Map.pdf">Herman Brown Hall for Mathematical Sciences</a>.'
url:              http://solar.rice.edu
baseurl:          /

author:
  name:           'Will Barnes'
  email:          'will.t.barnes@rice.edu'

include: ['_pages']

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb

paginate:         5
paginate_path: "page:num"

# Collections
#collections:
#  research:
#    output: true
#    permalink: /research/:path/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rice-solar-physics/group_webpage

#roles for people.
roles:
  - {key: faculty, name: Faculty}
  - {key: ressci, name: Research Scientists}
  - {key: grad, name: Graduate Students}
  - {key: ugrad, name: Undergraduate Students}
  - {key: alum, name: Alumni}

front_page_news: 5

#nav bar configuration
navigation:
    - title: Home
      link: /
    - title: People
      link: /People.html
    - title: Research
      link: /Research.html
    - title: Publications
      link: /Publications.html
    - title: Software
      link: /Software.html
    - title: Resources
      link: /Resources.html
