# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [smart,tables]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Solar@Rice
name:             Solar@Rice
description:      'The <b>Solar Physics Research Group</b> at <b>Rice University</b> uses computational modeling and observational tools to explore a variety of topics in solar and space plasma physics. Our current <a href="/Research.html">research projects</a> range from forward modeling of nanoflare-heated solar active regions to magnetic interactions between stars and planets. We are housed within the Department of Physics and Astronomy and located primarily in <a href="http://www.rice.edu/maps/Rice-University-Color-Campus-Map.pdf">Herman Brown Hall for Mathematical Sciences</a>.'
url:              http://solar.rice.edu
baseurl:          /

author:
  name:           'Will Barnes'
  email:          'will.t.barnes@rice.edu'

include: ['_pages','images']

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb

# Collections
collections:
  research:
    output: true
    permalink: research-topics/:path/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/rice-solar-physics/group_webpage

#roles for people.
roles:
  - {key: faculty, name: Faculty}
  - {key: ressci, name: Research Scientist}
  - {key: grad, name: Graduate Student}
  - {key: ugrad, name: Undergraduate Student}
  - {key: alum, name: Alumni}

front_page_news: 5

#pictures to display on the front page
front_page_pics:
  - img: images/loops_trace171.png
    description: "Image: NASA/LMSAL TRACE 171"
    width: 4
  - img: images/flare_sdoaia171.png
    description: "Image: NASA SDO/AIA 171"
    width: 4
  - img: images/star_planet_interaction.png
    description: "Image: A. Strugarek, U. Montréal"
    width: 4


#nav bar configuration
navigation:
    - title: Home
      link:
    - title: People
      link: People
    - title: Research
      link: Research
    - title: Publications
      link: Publications
    - title: Software
      link: Software
    - title: Resources
      link: Resources
