# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Solar @Rice
tagline:          'Rice Solar Physics Research Group webpage'
description:      'The Solar Physics Group, housed within the Dept. of Physics & Astronomy at Rice University, uses advanced numerical models to study plasma dynamics in the upper solar atmosphere.'
baseurl:          /
url:              http://rice-solar-physics.github.io

author:
  name:           'Will Barnes'
  email:          'will.t.barnes@rice.edu'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rice-solar-physics/rice-solar-physics.github.io
